revas-app/config/routes.rb
Rails.application.routes.draw do
  resources :sources
  resources :zip_codes
  devise_for :users
  resources :property_links
  get 'admin/index'
  get 'admin/dashboard'

  root 'admin#index'

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

revas-app/app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

revas-app/app/models/property_link.rb
class PropertyLink < ApplicationRecord
  
end

revas-app/app/models/source.rb
class Source < ApplicationRecord
end

revas-app/app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
  after_initialize :init_values

  private
  def init_values
    self.permission_level ||="ADMIN"
  end
end

revas-app/app/models/zip_code.rb
class ZipCode < ApplicationRecord

end

revas-app/app/controllers/admin_controller.rb
class AdminController < ApplicationController
  def index
    if user_signed_in?
      redirect_to "/admin/dashboard"
    else
      redirect_to new_user_session_path
    end
  end
  def dashboard
  end
end

revas-app/app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

revas-app/app/controllers/property_links_controller.rb
class PropertyLinksController < ApplicationController
  before_action :set_property_link, only: [:show, :edit, :update, :destroy]

  # GET /property_links
  # GET /property_links.json
  def index
    @property_links = PropertyLink.all
  end

  # GET /property_links/1
  # GET /property_links/1.json
  def show
  end

  # GET /property_links/new
  def new
    @property_link = PropertyLink.new
  end

  # GET /property_links/1/edit
  def edit
  end

  # POST /property_links
  # POST /property_links.json
  def create
    @property_link = PropertyLink.new(property_link_params)

    respond_to do |format|
      if @property_link.save
        format.html { redirect_to @property_link, notice: 'Property link was successfully created.' }
        format.json { render :show, status: :created, location: @property_link }
      else
        format.html { render :new }
        format.json { render json: @property_link.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /property_links/1
  # PATCH/PUT /property_links/1.json
  def update
    respond_to do |format|
      if @property_link.update(property_link_params)
        format.html { redirect_to @property_link, notice: 'Property link was successfully updated.' }
        format.json { render :show, status: :ok, location: @property_link }
      else
        format.html { render :edit }
        format.json { render json: @property_link.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /property_links/1
  # DELETE /property_links/1.json
  def destroy
    @property_link.destroy
    respond_to do |format|
      format.html { redirect_to property_links_url, notice: 'Property link was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_property_link
      @property_link = PropertyLink.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def property_link_params
      params.fetch(:property_link, {})
    end
end

revas-app/app/controllers/sources_controller.rb
class SourcesController < ApplicationController
  before_action :set_source, only: [:show, :edit, :update, :destroy]

  # GET /sources
  # GET /sources.json
  def index
    @sources = Source.all
  end

  # GET /sources/1
  # GET /sources/1.json
  def show
  end

  # GET /sources/new
  def new
    @source = Source.new
  end

  # GET /sources/1/edit
  def edit
  end

  # POST /sources
  # POST /sources.json
  def create
    @source = Source.new(source_params)

    respond_to do |format|
      if @source.save
        format.html { redirect_to @source, notice: 'Source was successfully created.' }
        format.json { render :show, status: :created, location: @source }
      else
        format.html { render :new }
        format.json { render json: @source.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /sources/1
  # PATCH/PUT /sources/1.json
  def update
    respond_to do |format|
      if @source.update(source_params)
        format.html { redirect_to @source, notice: 'Source was successfully updated.' }
        format.json { render :show, status: :ok, location: @source }
      else
        format.html { render :edit }
        format.json { render json: @source.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /sources/1
  # DELETE /sources/1.json
  def destroy
    @source.destroy
    respond_to do |format|
      format.html { redirect_to sources_url, notice: 'Source was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_source
      @source = Source.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def source_params
      params.require(:source).permit(:name, :url)
    end
end

revas-app/app/controllers/zip_codes_controller.rb
class ZipCodesController < ApplicationController
  before_action :set_zip_code, only: [:show, :edit, :update, :destroy]

  # GET /zip_codes
  # GET /zip_codes.json
  def index
    @zip_codes = ZipCode.all
  end

  # GET /zip_codes/1
  # GET /zip_codes/1.json
  def show
  end

  # GET /zip_codes/new
  def new
    @zip_code = ZipCode.new
  end

  # GET /zip_codes/1/edit
  def edit
  end

  # POST /zip_codes
  # POST /zip_codes.json
  def create
    @zip_code = ZipCode.new(zip_code_params)

    respond_to do |format|
      if @zip_code.save
        format.html { redirect_to @zip_code, notice: 'Zip code was successfully created.' }
        format.json { render :show, status: :created, location: @zip_code }
      else
        format.html { render :new }
        format.json { render json: @zip_code.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /zip_codes/1
  # PATCH/PUT /zip_codes/1.json
  def update
    respond_to do |format|
      if @zip_code.update(zip_code_params)
        format.html { redirect_to @zip_code, notice: 'Zip code was successfully updated.' }
        format.json { render :show, status: :ok, location: @zip_code }
      else
        format.html { render :edit }
        format.json { render json: @zip_code.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /zip_codes/1
  # DELETE /zip_codes/1.json
  def destroy
    @zip_code.destroy
    respond_to do |format|
      format.html { redirect_to zip_codes_url, notice: 'Zip code was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_zip_code
      @zip_code = ZipCode.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def zip_code_params
      params.require(:zip_code).permit(:zipcode, :city, :county, :state, :country)
    end
end

revas-app/app/helpers/admin_helper.rb
module AdminHelper
end

revas-app/app/helpers/application_helper.rb
module ApplicationHelper
end

revas-app/app/helpers/property_links_helper.rb
module PropertyLinksHelper
end

revas-app/app/helpers/sources_helper.rb
module SourcesHelper
end

revas-app/app/helpers/zip_codes_helper.rb
module ZipCodesHelper
end

revas-app/app/views/admin/dashboard.html.erb
          <h1>Dashboard</h1>

          <div class="row" style="padding-top: 20px;">
            <div class="col-xs-6 col-sm-3">
            <div class="card" >
              <div class="card-block">
                <h4>Collectors</h4>
                <span class="text-muted">Urls Collected: </span>
              </div>

            </div>

            </div>
            <div class="col-xs-6 col-sm-3">
              <div class="card">
                <div class="card-block">
                  <h4>Miners</h4>
                  <span class="text-muted">Properties Mined: </span>
                </div>

              </div>
            </div>

          </div>

          <h2>Properties Summary</h2>
          <div class="table-responsive">
            <table class="table table-striped">
              <thead>
                <tr>
                  <th>#</th>
                  <th>Header</th>
                  <th>Header</th>
                  <th>Header</th>
                  <th>Header</th>
                </tr>
              </thead>
              <tbody>
                <tr>
                  <td>1,001</td>
                  <td>Lorem</td>
                  <td>ipsum</td>
                  <td>dolor</td>
                  <td>sit</td>
                </tr>

              </tbody>
            </table>
          </div>
        </div>
      </div>
    </div>

revas-app/app/views/admin/index.html.erb
<div class="container">
      <form class="form-signin">
        <h2 class="form-signin-heading">Please, sign in</h2>
        <label for="inputEmail" class="sr-only">Email address</label>
        <input type="email" id="inputEmail" class="form-control" placeholder="Email address" required autofocus>
        <label for="inputPassword" class="sr-only">Password</label>
        <input type="password" id="inputPassword" class="form-control" placeholder="Password" required>
        <div class="checkbox">
          <label>
            <input type="checkbox" value="remember-me"> Remember me
          </label>
        </div>
        <button class="btn btn-primary btn-block" type="submit">Sign in</button>
      </form>

</div> <!-- /container -->

revas-app/app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>RevasApp</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <nav class="navbar navbar-dark navbar-fixed-top bg-inverse">
          <button type="button" class="navbar-toggler hidden-sm-up" data-toggle="collapse" data-target="#navbar" aria-expanded="false" aria-controls="navbar" aria-label="Toggle navigation"></button>
          <a class="navbar-brand" href="#">Revas Admin Manager</a>
          <div id="navbar">
            <nav class="nav navbar-nav float-xs-left">
              <%if user_signed_in?%>
                  <a class="nav-item nav-link" href="#">Dashboard</a>
                  <a class="nav-item nav-link" href="#">Settings</a>
                  <a class="nav-item nav-link" href="#">Profile</a>
                  <a class="nav-item nav-link" href="#">Help</a>
                  <%= link_to "Logout", destroy_user_session_path, method: :delete, class:"nav-item nav-link" %>
              <%end%>
            </nav>

          </div>
        </nav>

        <div class="container-fluid">
          <div class="row">
            <div class="col-sm-3 col-md-2 sidebar pull-right">
              <ul class="nav nav-sidebar">
                <%if user_signed_in?%>
                  <li class="active"><a href="#">Overview <span class="sr-only">(current)</span></a></li>
                  <li><a href="/zip_codes">Zip Codes</a></li>
                  <li><%= link_to 'Sources', sources_path%></li>
                  <li><a href="#">Properties Collectors</a></li>
                  <li><%= link_to 'Properties Information', property_links_path %></li>
                  <li><a href="#">Export</a></li>
                <%end%>
              </ul>

            </div>
              <div class="col-sm-9 offset-sm-3 col-md-10 offset-md-2 main">
                  <%= yield %>
              </div>
      </div>
    </div>
  </body>
</html>

revas-app/app/views/property_links/_form.html.erb
<%= form_for(property_link, :html => {:class => "form-group"}) do |f| %>
  <% if property_link.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(property_link.errors.count, "error") %> prohibited this property_link from being saved:</h2>

      <ul>
      <% property_link.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>

      </ul>
    </div>
  <% end %>
  <%=f.label :property_url %>
  <%=f.text_field :property_url, autofocus:true, class:"form-control"%>
  <%=f.label :address %>
  <%=f.text_field :address, class:"form-control"   %>
  <%=f.label :city %>
  <%=f.text_field :city, class:"form-control"   %>
  <%=f.label :state %>
  <%=f.text_field :state, class:"form-control"   %>
  <%=f.label :country %>
  <%=f.text_field :country, class:"form-control"   %>
  <%=f.label :postal_code %>
  <%=f.text_field :postal_code, class:"form-control"   %>
  <%=f.label :latitude %>
  <%=f.text_field :latitude, class:"form-control"   %>
  <%=f.label :longitude %>
  <%=f.text_field :longitude, class:"form-control"   %>
  <%=f.label :foreclosure_status %>
  <%=f.text_field :foreclosure_status, class:"form-control"   %>
  <%=f.label :price %>
  <%=f.text_field :price, class:"form-control"   %>
  <%=f.label :source %>
  <%=f.text_field :source, class:"form-control custom-select"   %>

  <div class="actions">
    <%= f.submit %>
  </div>
  <%= link_to 'Back', property_links_path %>
<% end %>

revas-app/app/views/property_links/edit.html.erb
<h1>Editing Property Link</h1>

<%= render 'form', property_link: @property_link %>

<%= link_to 'Show', @property_link %> |
<%= link_to 'Back', property_links_path %>

revas-app/app/views/property_links/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Property Links</h1>

<table>
  <thead>
    <tr>
      <th>Id</th>
      <th>Property Url</th>
      <th>Address</th>
      <th>City</th>
      <th>State</th>
      <th>Country</th>
      <th>Postal Code</th>
      <th>Latitude</th>
      <th>Longitude</th>
      <th>F. Status</th>
      <th>Price</th>
      <th>Source</th>
      <th>Created At</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @property_links.each do |property_link| %>
      <tr>
        <td><%= property_link.id %></td>
        <td><%= property_link.property_url %></td>
        <td><%= property_link.address %></td>
        <td><%= property_link.city %></td>
        <td><%= property_link.state %></td>
        <td><%= property_link.country %></td>
        <td><%= property_link.postal_code %></td>
        <td><%= property_link.latitude %></td>
        <td><%= property_link.longitude %></td>
        <td><%= property_link.foreclosure_status %></td>
        <td><%= property_link.price %></td>
        <td><%= property_link.source %></td>
        <td><%= property_link.created_at %></td>
        <td><%= link_to 'Show', property_link %></td>
        <td><%= link_to 'Edit', edit_property_link_path(property_link) %></td>
        <td><%= link_to 'Destroy', property_link, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Property Link', new_property_link_path %>

revas-app/app/views/property_links/new.html.erb
<h1>New Property Link</h1>

<%= render 'form', property_link: @property_link %>

revas-app/app/views/property_links/show.html.erb
<p id="notice"><%= notice %></p>
<p>
  Id:
  <%= @property_link.id %>
</p>
<p>
  Property Url:
  <%= @property_link.property_url %>
</p>
<p>
  Address:
  <%= @property_link.address %>
</p>
<p>
  City:
  <%= @property_link.city %>
</p>
<p>
  State:
  <%= @property_link.state %>
</p>
<p>
  Country:
  <%= @property_link.country %>
</p>
<p>
  Postal Code:
  <%= @property_link.postal_code %>
</p>
<p>
  Latitude:
  <%= @property_link.latitude %>
</p>
<p>
  Longitude:
  <%= @property_link.longitude %>
</p>
<p>
  Foreclosure Status:
  <%= @property_link.foreclosure_status %>
</p>
<p>
  Price:
  <%= @property_link.price %>
</p>
<p>
  Source:
  <%= @property_link.source %>
</p>
<p>
  Created At:
  <%= @property_link.created_at %>
</p>

<%= link_to 'Edit', edit_property_link_path(@property_link) %> |
<%= link_to 'Back', property_links_path %>

revas-app/app/views/sources/_form.html.erb
<%= form_for(source) do |f| %>
  <% if source.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(source.errors.count, "error") %> prohibited this source from being saved:</h2>

      <ul>
      <% source.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %>
    <%= f.text_field :name %>
  </div>

  <div class="field">
    <%= f.label :url %>
    <%= f.text_field :url %>
  </div>

  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

revas-app/app/views/sources/edit.html.erb
<h1>Editing Source</h1>

<%= render 'form', source: @source %>

<%= link_to 'Show', @source %> |
<%= link_to 'Back', sources_path %>

revas-app/app/views/sources/index.html.erb
<h1>Sources</h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th>Url</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @sources.each do |source| %>
      <tr>
        <td><%= source.name %></td>
        <td><%= source.url %></td>
        <td><%= link_to 'Show', source %></td>
        <td><%= link_to 'Edit', edit_source_path(source) %></td>
        <td><%= link_to 'Destroy', source, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Source', new_source_path %>

revas-app/app/views/sources/new.html.erb
<h1>New Source</h1>

<%= render 'form', source: @source %>

<%= link_to 'Back', sources_path %>

revas-app/app/views/sources/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @source.name %>
</p>

<p>
  <strong>Url:</strong>
  <%= @source.url %>
</p>

<%= link_to 'Edit', edit_source_path(@source) %> |
<%= link_to 'Back', sources_path %>

revas-app/app/views/zip_codes/_form.html.erb
<%= form_for(zip_code) do |f| %>
  <% if zip_code.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(zip_code.errors.count, "error") %> prohibited this zip_code from being saved:</h2>

      <ul>
      <% zip_code.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :zipcode %>
    <%= f.text_field :zipcode %>
  </div>

  <div class="field">
    <%= f.label :city %>
    <%= f.text_field :city %>
  </div>

  <div class="field">
    <%= f.label :county %>
    <%= f.text_field :county %>
  </div>

  <div class="field">
    <%= f.label :state %>
    <%= f.text_field :state %>
  </div>

  <div class="field">
    <%= f.label :country %>
    <%= f.text_field :country %>
  </div>

  <div class="field">
    <%= f.label :latitude %>
    <%= f.text_field :latitude %>
  </div>

  <div class="field">
    <%= f.label :longitude %>
    <%= f.text_field :longitude %>
  </div>

  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

revas-app/app/views/zip_codes/edit.html.erb
<h1>Editing Zip Code</h1>

<%= render 'form', zip_code: @zip_code %>

<%= link_to 'Show', @zip_code %> |
<%= link_to 'Back', zip_codes_path %>

revas-app/app/views/zip_codes/index.html.erb
<h1>Zip Codes</h1>

<table>
  <thead>
    <tr>
      <th>Zipcode</th>
      <th>City</th>
      <th>County</th>
      <th>State</th>
      <th>Country</th>
      <th>Latitude</th>
      <th>Longitude</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @zip_codes.each do |zip_code| %>
      <tr>
        <td><%= zip_code.zipcode %></td>
        <td><%= zip_code.city %></td>
        <td><%= zip_code.county %></td>
        <td><%= zip_code.state %></td>
        <td><%= zip_code.country %></td>
        <td><%= zip_code.latitude %></td>
        <td><%= zip_code.longitude %></td>
        <td><%= link_to 'Show', zip_code %></td>
        <td><%= link_to 'Edit', edit_zip_code_path(zip_code) %></td>
        <td><%= link_to 'Destroy', zip_code, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Zip Code', new_zip_code_path %>

revas-app/app/views/zip_codes/new.html.erb
<h1>New Zip Code</h1>

<%= render 'form', zip_code: @zip_code %>

<%= link_to 'Back', zip_codes_path %>

revas-app/app/views/zip_codes/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Zipcode:</strong>
  <%= @zip_code.zipcode %>
</p>

<p>
  <strong>City:</strong>
  <%= @zip_code.city %>
</p>

<p>
  <strong>County:</strong>
  <%= @zip_code.county %>
</p>

<p>
  <strong>State:</strong>
  <%= @zip_code.state %>
</p>

<p>
  <strong>Country:</strong>
  <%= @zip_code.country %>
</p>
<p>
  <strong>latitude:</strong>
  <%= @zip_code.latitude %>
</p>
<p>
  <strong>longitude:</strong>
  <%= @zip_code.longitude %>
</p>

<%= link_to 'Edit', edit_zip_code_path(@zip_code) %> |
<%= link_to 'Back', zip_codes_path %>